FROM node:13-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
# RUN npm install
# RUN npm install react-script@3.0.1 -g

# start app
# CMD ["yarn", "start"]
# Khi yarn start ko dc, mở yarn install ra cho up --build rồi thử lại